### ISSUE TITLE
options are not strictly parsed (prefix error)

### ISSUE THREAD

**Issue by zkraus** [sgraf-pub/iso-validator#1]
speicified "--arc" and it was passed as arch. Since this is user friendlier, it could cause some problem in the future.

~/src/iso-validator/iso-analysis.py --new-iso iso/my_iso.iso --arc x86_64
# Analysing iso/my_iso.iso as new iso

ISO Analysing files
ISO Analysing packages
# Skipping tests requiring old iso
# Skipping tests requiring Key ID
# Skipping tests requiring source content (new)
# Package tests: wrong arch (new iso only)

set([  ## Omitting packages ## ])
# Skipping tests requiring repos

**Comment by sgraf-pub** [comment]
I think this is a feature/property of optparse, library I used.
