### ISSUE TITLE
Usage in readme does not reflect most recent program version

### ISSUE THREAD

**Issue by zkraus** [sgraf-pub/iso-validator#2]
README version:
$ ./iso_analysis.py -h
Usage: iso_analysis.py [options]

Options:
  -h, --help         show this help message and exit
  --new_iso=NEW_ISO  URI of ISO image for validation (new)
  --old_iso=OLD_ISO  URI of ISO image for reference (old)
  --arch=ARCH        Target architecture (x86_64, i686...)
  --key_id=KEY_ID    Package signing Key ID
  --repo_comparison  Compare ISO packages NVRs to the available yum repos

Program Version:
$ ./iso-analysis.py --help
Usage: iso-analysis.py [options]

Options:
  -h, --help            show this help message and exit
  --new-iso=NEW_ISO     URI of binary content for validation (new)
  --source-iso=SOURCE_ISO
                        URI of source content for validation (new)
  --old-iso=OLD_ISO     URI of content for reference (old)
  --arch=ARCH           Target architecture (x86_64, i686...)
  --key-id=KEY_ID       Package signing Key ID (can be specified multiple
                        times)
  --repo-comparison     Compare ISO packages NVRs to the available yum repos
  --repofrompath=REPOFROMPATH
                        Specify repoid & paths of additional repositories -
                        unique repoid and complete path required, can be
                        specified multiple times. Example.
                        --repofrompath=myrepo,/path/to/repo

**Comment by sgraf-pub** [comment]
Fixed
https://github.com/sgraf-pub/iso-validator/commit/24c028596b723e89acaa2f12ce76f9deecf1201e
